# Generated by Django 3.1.1 on 2020-09-22 22:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Museum or private collection')),
            ],
        ),
        migrations.CreateModel(
            name='Glyph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('number_in_line', models.IntegerField(default=0, verbose_name='Sequence of glyph in line')),
                ('number_in_page', models.IntegerField(blank=True, null=True, verbose_name='Sequence of glyph in page')),
                ('unicode_glyphs', models.CharField(blank=True, max_length=50, verbose_name='Unicode hieroglyphs')),
                ('manuel_de_codage', models.CharField(blank=True, max_length=100, verbose_name='Manuel de Codage hieroglyphs')),
                ('moller_number', models.CharField(blank=True, max_length=50, verbose_name="Entry number in Möller's Palaeographie")),
                ('mainz_number', models.CharField(blank=True, max_length=100, verbose_name='Entry number in Mainz Palaeographie')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('number_in_page', models.IntegerField(default=0, verbose_name='Sequence of line in page')),
                ('number_in_manuscript', models.IntegerField(null=True, verbose_name='Sequence of line in manuscript as a whole')),
                ('testshape', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(blank=True, max_length=200, verbose_name='Accession number')),
                ('find_date', models.CharField(blank=True, max_length=300, verbose_name='Date found in modern era')),
                ('provenance', models.CharField(blank=True, max_length=200, verbose_name='Geographic location of origin')),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date added to the database')),
                ('marked_for_deletion', models.BooleanField(default=False, verbose_name='Removing a text triggers more operations')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sobti.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon_type', models.CharField(blank=True, default='Empty', max_length=5, verbose_name='Type of polygon (line or glyph)')),
                ('x_min', models.IntegerField()),
                ('y_min', models.IntegerField()),
                ('x_max', models.IntegerField()),
                ('y_max', models.IntegerField()),
                ('x_cent', models.IntegerField()),
                ('y_cent', models.IntegerField()),
                ('glyph', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sobti.glyph')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sobti.line')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oclc', models.CharField(blank=True, max_length=500, verbose_name='OCLC of source.')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Name of text')),
                ('era_composed', models.CharField(blank=True, max_length=200, verbose_name="Approximate date of the text's original composition")),
            ],
        ),
        migrations.CreateModel(
            name='PolygonPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.IntegerField()),
                ('y_coordinate', models.IntegerField()),
                ('t_coordinate', models.IntegerField(verbose_name='Position in sequence of points')),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sobti.polygon')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_manuscript', models.IntegerField(verbose_name='Page number in manuscript')),
                ('image', models.FileField(upload_to='upload/%Y-%m-%d')),
                ('image_preview', models.ImageField(blank=True, upload_to='')),
                ('image_thumbnail', models.ImageField(blank=True, upload_to='')),
                ('horizont', models.BooleanField(default=True, verbose_name='Text is horizontal (not vertical)')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sobti.manuscript')),
            ],
        ),
        migrations.AddField(
            model_name='manuscript',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sobti.text'),
        ),
        migrations.AddField(
            model_name='line',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sobti.page'),
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Layer number in PSD')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sobti.page')),
            ],
        ),
        migrations.AddField(
            model_name='glyph',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sobti.line'),
        ),
        migrations.CreateModel(
            name='BibEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sobti.source')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sobti.text')),
            ],
        ),
    ]
