# Generated by Django 3.1.1 on 2020-09-22 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sobti', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='testshape',
            new_name='shape',
        ),
    ]
