# Generated by Django 3.0.5 on 2020-05-08 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sobti', '0003_remove_page_image_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glyph',
            name='polygon',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Sobti.Polygon'),
        ),
        migrations.AlterField(
            model_name='line',
            name='polygon',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Sobti.Polygon'),
        ),
    ]
