# Generated by Django 3.0.5 on 2020-05-08 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sobti', '0004_auto_20200507_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='image_file_name',
        ),
        migrations.AlterField(
            model_name='line',
            name='polygon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sobti.Polygon'),
        ),
    ]
