# Generated by Django 3.0.5 on 2020-05-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sobti', '0006_auto_20200507_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='glyph',
            name='number_in_page',
            field=models.IntegerField(null=True, verbose_name='Sequence of glyph in page'),
        ),
    ]
