# Generated by Django 3.0.5 on 2020-05-08 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sobti', '0008_auto_20200507_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glyph',
            name='polygon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sobti.Polygon'),
        ),
        migrations.AlterField(
            model_name='line',
            name='polygon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Sobti.Polygon'),
        ),
    ]
