# Generated by Django 3.0.5 on 2020-05-08 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sobti', '0009_auto_20200507_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glyph',
            name='polygon',
        ),
        migrations.RemoveField(
            model_name='line',
            name='polygon',
        ),
        migrations.AddField(
            model_name='polygon',
            name='glyph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sobti.Glyph'),
        ),
        migrations.AddField(
            model_name='polygon',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sobti.Line'),
        ),
        migrations.AddField(
            model_name='polygon',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sobti.Page'),
        ),
        migrations.AlterField(
            model_name='glyph',
            name='number_in_line',
            field=models.IntegerField(default=0, verbose_name='Sequence of glyph in line'),
        ),
        migrations.AlterField(
            model_name='glyph',
            name='number_in_page',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sequence of glyph in page'),
        ),
        migrations.AlterField(
            model_name='line',
            name='number_in_page',
            field=models.IntegerField(default=0, verbose_name='Sequence of line in page'),
        ),
    ]
