# Generated by Django 3.0.5 on 2020-05-08 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sobti', '0010_auto_20200507_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygon',
            name='glyph',
        ),
        migrations.RemoveField(
            model_name='polygon',
            name='line',
        ),
        migrations.RemoveField(
            model_name='polygon',
            name='page',
        ),
    ]
