# Generated by Django 3.0.5 on 2020-05-08 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sobti', '0011_auto_20200507_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='glyph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sobti.Glyph'),
        ),
        migrations.AddField(
            model_name='polygon',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sobti.Line'),
        ),
        migrations.AddField(
            model_name='polygon',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sobti.Page'),
        ),
    ]
