# Generated by Django 3.0.5 on 2020-05-08 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sobti', '0012_auto_20200507_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygon',
            name='page',
        ),
    ]
