# Generated by Django 3.0.5 on 2020-05-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sobti', '0013_remove_polygon_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='polygon_type',
            field=models.CharField(blank=True, default='Empty', max_length=16, verbose_name='Type of polygon (line or glyph)'),
        ),
    ]
