# Generated by Django 3.0.5 on 2020-05-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sobti', '0014_auto_20200507_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='polygon_type',
            field=models.CharField(blank=True, default='Empty', max_length=5, verbose_name='Type of polygon (line or glyph)'),
        ),
    ]
