# Generated by Django 3.0.5 on 2020-05-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sobti', '0015_auto_20200507_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glyph',
            name='image',
        ),
        migrations.RemoveField(
            model_name='line',
            name='image',
        ),
        migrations.AddField(
            model_name='glyph',
            name='image_filename',
            field=models.CharField(default='', max_length=300, verbose_name='Name of glyph image minus extension'),
        ),
        migrations.AddField(
            model_name='line',
            name='image_filename',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Name of line image minus extension'),
        ),
    ]
