# Generated by Django 3.0.5 on 2020-05-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sobti', '0016_auto_20200507_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
