# Generated by Django 3.0.5 on 2020-05-08 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sobti', '0017_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Sobti.Page'),
            preserve_default=False,
        ),
    ]
