# Generated by Django 3.0.5 on 2020-05-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sobti', '0019_line_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Layer number in PSD'),
        ),
    ]
