# Generated by Django 3.0.5 on 2020-05-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sobti', '0020_layer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glyph',
            name='image_filename',
        ),
        migrations.RemoveField(
            model_name='line',
            name='image_filename',
        ),
        migrations.AddField(
            model_name='glyph',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
