# Generated by Django 3.0.5 on 2020-05-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sobti', '0021_auto_20200508_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='x_cent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polygon',
            name='x_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polygon',
            name='x_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polygon',
            name='y_cent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polygon',
            name='y_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polygon',
            name='y_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
